# Generated by Django 3.2.7 on 2022-06-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_mybill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybill',
            name='billName',
            field=models.CharField(choices=[('shop rent', 'Shop Rent'), ('electricity bill', 'Electricity Bill'), ('wifi bill', 'Wifi Bill'), ('donation', 'Donation'), ('tea bill', 'Tea Bill'), ('customer related', 'Customer Related'), ('friends related', 'Friends Related'), ('others', 'others')], max_length=50),
        ),
    ]
